### PR TITLE
update to build PR

### PR DESCRIPTION
**Pull request by jread-usgs**
@lawinslow can you comment out `rloadest` locally? seems fine on mac.

### CODE REVIEW

**Comment by lawinslow** [comment]
Are you building the vignettes?

**Comment by jread-usgs** [comment]
trying w/ vignettes now.

**Comment by jread-usgs** [comment]
I fail building `EflowStats` vignette, before I reach `rloadest`

**Comment by jread-usgs** [comment]
https://stat.ethz.ch/pipermail/bioc-devel/2013-August/004583.html

I get a lot of these errors: 

``R
Error in texi2dvi(file = file, pdf = TRUE, clean = clean, quiet = quiet,  : 
  Running 'texi2dvi' on 'EflowStats.tex' failed.
LaTeX errors:
! LaTeX Error: Unknown float option `{'.
```

**Comment by lawinslow** [comment]
Are all your local packages updated?

**Comment by lawinslow** [comment]
Ugh, vignettes

**Pull request merged**
