### PR TITLE
add wrv to gran source list

### PR DESCRIPTION
**Pull request by jfisher-usgs**
Status: 2 NOTEs

* checking installed package size ... NOTE
  installed size is 392.7Mb

The package will be about 100Mb after reducing the file size of the vignette PDF files using an Adobe Acrobat tool.

* checking R code for possible problems ... NOTE
RunWaterBalance : FUN: no visible binding for global variable 'div.sw'
...

This note concerns my coding style... shouldn't be a problem.

### CODE REVIEW

**Comment by lawinslow** [comment]
Want to squash that with a globalVariables call?
http://stackoverflow.com/questions/9439256/how-can-i-handle-r-cmd-check-no-visible-binding-for-global-variable-notes-when

And 392 Mb? What's in this package?

**Comment by jfisher-usgs** [comment]
Thanks for the info on globalVariables; I'll look into implementing this call for future version of the wrv package. As far as the package size being 392 MB, keep in mind that the package contains all necessary datasets for building a groundwater flow model of the Wood River Valley aquifer system. If you can believe it, these datasets were created (with some processing) from raw datasets in order to reduce the overall size of the package.

**Comment by jfisher-usgs** [comment]
It also just occurred to me that the package size is so large because the vignette PDF files have not yet been optimized for viewing. I'm using the Adobe Acrobat PDF Optimizer to reduce the size of these files (see "1.6.1 PDF size" section in the Writing R Extensions manual, pg. 49). With updated PDF files the package is around 100 MB.

**Comment by jfisher-usgs** [comment]
Same NOTES as before

**Pull request merged**
