### PR TITLE
fixing hazard items release name

### PR DESCRIPTION
**Pull request by lawinslow**
@mhines-usgs: Be careful with your release versions. The names need to match.

### CODE REVIEW

**Comment by mhines-usgs** [comment]
@lawinslow crud, thank you:)

**Comment by ldecicco-USGS** [comment]
I'll probably cut a few releases this morning if you guys can wait.

**Comment by lawinslow** [comment]
np, we've all done it

**Comment by lawinslow** [comment]
ok, go for it @ldecicco-USGS

**Comment by lawinslow** [comment]
@jread-usgs @dlorenz-usgs @aappling-usgs anybody else on the release train?

**Pull request merged**
