### PR TITLE
adding wq-review to GRAN

### PR DESCRIPTION
**Pull request by tmills-usgs**

### CODE REVIEW

**Comment by tmills-usgs** [comment]
One more modification. Added importFrom DT renderDataTable and importFrom DT dataTableOutput to overwrite the deprecated Shiny data tables. Also removed unnecessary packages from description file. The note mentioned in the previous commit still applies but now build produces 1 warning. The warning occurs because of the DT import overwriting the shiny namespace. This can't be fixed until shiny removes the two overlapping functions. Only way around it (that I know of) is to import each function individually form shiny, omitting the two from DT. However, this would require importing a huge number of individual functions.

**Comment by ldecicco-USGS** [comment]
@tmills-usgs we good to go with this?

**Comment by tmills-usgs** [comment]
yup

**Comment by tmills-usgs** [comment]
So is this up on GRAN now?

**Comment by ldecicco-USGS** [comment]
After I merge the pull request, it takes ~15 minutes for the script to run everything and push it up to the owi server. The source and Windows binaries should be up by 10:15ish. Do you need Mac binaries right away? We haven't automated those yet. They will definitely be up in the next couple days, but if you have Mac users, we can bump up the priority.

**Comment by tmills-usgs** [comment]
No need for Mac. Thanks Laura!

**Comment by ldecicco-USGS** [comment]
Source and windows binaries are up.

**Comment by jread-usgs** [comment]
@tmills-usgs let me know if the mac becomes a priority. Otherwise they will be up later in the week (Thurs?).

**Comment by tmills-usgs** [comment]
I am still not seeing the package listed on GRAN.

```r
GRAN_pkg <- available.packages(contrib.url("http://owi.usgs.gov/R"))
names(GRAN_pkg[,1])
```

**Comment by ldecicco-USGS** [comment]
Hmm...restart RStudio? Shows up for me:

**Comment by jread-usgs** [comment]
I see it too (nice screenshot LDC!)

**Comment by tmills-usgs** [comment]
:scream: There it is! restart fixed it. Thanks!

**Pull request merged**
