### PR TITLE
for geoknife v1.0.0 and some readme thingies

### PR DESCRIPTION
**Pull request by jread-usgs**

### CODE REVIEW

**Comment by jread-usgs** [comment]
@ldecicco-USGS or @lawinslow ?

**Comment by ldecicco-USGS** [comment]
Today?

**Comment by jread-usgs** [comment]
oh, I just wanted someone else to merge the PR or comment and/or suggest changes

**Comment by ldecicco-USGS** [comment]
Looks fine to me. Ohhh...github's telling me to run continuous integration!

**Comment by lawinslow** [comment]
Ha, that's a new message.

**Pull request merged**
