### PR TITLE
Update Graphs v1.0.7

### PR DESCRIPTION
**Pull request by dlorenz-usgs**

### CODE REVIEW

**Comment by jread-usgs** [comment]
has tag, version correct. Any notes or warnings that need to be explained?

**Comment by jread-usgs** [comment]
looks like two `NOTES` from the build. One was travis script that wasn't in `.buildignore`, the other is 
```R
Found the following assignments to the global environment:
File ‘smwrGraphs/R/setPage.R’:
  assign(".SavedPlots", NULL, envir = .GlobalEnv)
```

**Comment by ldecicco-USGS** [comment]
I'm going to merge this, but @dlorenz-usgs , that's our new policy. If there are any notes or warnings, and you think they are justifiable, then you need to list and explain them here in the pull request.

**Comment by dlorenz-usgs** [comment]
I think the policy on Notes is good and I do not like doing what I've had
to do in the setPage function to manage the saved plots in Windows. I can
find no support functions for managing those plots. Any ideas?

**Comment by ldecicco-USGS** [comment]
I've never really understood the nuances of this function (setPage). Maybe we should schedule a webex one of these days when Jordan/Luke/Emily/myself can all discuss. Then, we might be able to help out a bit more effectively.

**Comment by dlorenz-usgs** [comment]
Understanding the nuances of setPage would be key to understanding how the
graphics environment for smwrGraphs is set up. I'm out on Thursday and have
reviews scatter all of the next 2 weeks.

**Comment by ldecicco-USGS** [comment]
OK, let's figure out another time. Why don't you suggest some times that work for you. Side note: all the packages are compiled and ready to ship out to GRAN...I'm just have trouble with Amazon now. We've got a ticket to their service desk. Hopefully it gets straightened out pretty quickly.

**Comment by dlorenz-usgs** [comment]
That time worked. I had not seen your invitation before I responded.

**Pull request merged**
