### PR TITLE
Update to GLMr

### PR DESCRIPTION
**Pull request by lawinslow**

### CODE REVIEW

**Comment by lawinslow** [comment]
We can do double-duty while we're at it.

**Comment by ldecicco-USGS** [comment]
I'm going to have a EGRETci one very soon too...in case anyone started this.

**Comment by lawinslow** [comment]
everyone pile on the gran train

**Comment by ldecicco-USGS** [comment]
choo choo!

**Comment by lawinslow** [comment]
:steam_locomotive:

**Pull request merged**
