### PR TITLE
Added citation files.

### PR DESCRIPTION
**Pull request by ldecicco-USGS**

### CODE REVIEW

**Comment by ldecicco-USGS** [comment]
@lawinslow , I'm done with my futzing here. Proceed if you trust me.

**Comment by lawinslow** [comment]
so much trust

**Comment by lawinslow** [comment]
@ldecicco-USGS back to you for mac

**Comment by ldecicco-USGS** [comment]
Something's amiss...will troubleshoot in the morning.

**Comment by ldecicco-USGS** [comment]
Well, it worked this morning, not sure what was going on last night. All's good.

**Pull request merged**
