### PR TITLE
Adding hydro opt package

### PR DESCRIPTION
**Pull request by ldecicco-USGS**

### CODE REVIEW

**Comment by lawinslow** [comment]
image
@ldecicco-USGS Tab delimited??

**Comment by jread-usgs** [comment]
:-1:

**Comment by ldecicco-USGS** [comment]
Gah, why does that never work in RStudio?

**Comment by jread-usgs** [comment]
:cry:

**Comment by ldecicco-USGS** [comment]
Same with editing .yml's...fixing in notepad

**Comment by lawinslow** [comment]
The data retrieval tag is not v2.1.1, it's just 2.1.1. Please fix the tags.

**Comment by lawinslow** [comment]
https://github.com/USGS-R/dataRetrieval/releases

vs

https://github.com/USGS-R/geoknife/releases

**Comment by ldecicco-USGS** [comment]
OK, I changed EGRET, dataRetrieval, and hydrotools...I never would have guessed that would be the way we want it.

**Comment by ldecicco-USGS** [comment]
Do tabs work right in RStudio on the Macs?

**Comment by jread-usgs** [comment]
well...you can tag your release however you want to. But yeah, we should probably have some kind of convention.

**Comment by jread-usgs** [comment]
yes

**Comment by ldecicco-USGS** [comment]
Wonder if that's  a bug

**Comment by ldecicco-USGS** [comment]
The v seems silly to me, but I'll do it. As long as the gran_source_list is correct, it will work though, right?

**Comment by lawinslow** [comment]
Yeah, the v is silly, but I don't know how else you'd want it. The only thing the downloader knows is the tag name. The tag name can be whatever you want e.g., "hearty heron". So if you put one name into github, then a different name into grantools, there's no way to rectify it.

**Comment by lawinslow** [comment]
src and windows done. @ldecicco-USGS your turn.

**Pull request merged**
