### PR TITLE
new version of smwrQW

### PR DESCRIPTION
**Pull request by dlorenz-usgs**
updated .tsv file for new version of smwrQW

### CODE REVIEW

**Comment by jread-usgs** [comment]
I couldn't pkg check due to a vignette issue (probably my LaTeX). @dlorenz-usgs any notes or warnings on this version after pkg check?

**Comment by dlorenz-usgs** [comment]
There are warnings from the R functions that are called within the scripts.
They are expected. Is that the problem?

**Comment by jread-usgs** [comment]
@dlorenz-usgs to be clear, when you run `R CMD check` on the package, does it return any warnings? I am just asking about -8 in the list here: http://owi.usgs.gov/R/gran.html#add_package

**Comment by jread-usgs** [comment]
Warning from smwrQW check:
`* checking if this is a source package ... WARNING
Subdirectory ‘src’ contains:
  fmodules.inc
These are unlikely file names for src files.`

**Comment by dlorenz-usgs** [comment]
I was told to ignore the .inc suffix although I suggested it would be easy
to change to .h.

**Comment by ldecicco-USGS** [comment]
Yeah, that's fine, I didn't properly document the first pull request, my bad.

**Comment by jread-usgs** [comment]
All good here Dave.

**Pull request merged**
