### PR TITLE
Course package.

### PR DESCRIPTION
**Pull request by ldecicco-USGS**

### CODE REVIEW

**Comment by lawinslow** [comment]
```R

* checking for file 'C:\Windows\Temp\RtmpQdPDPX\usgs-r\gsIntroR\gsIntroR-0.1.1/DESCRIPTION' ... OK
* preparing 'gsIntroR':
* checking DESCRIPTION meta-information ... OK
* installing the package to build vignettes
* creating vignettes ...Warning: running command '"C:/PROGRA~1/R/R-31~1.3/bin/i386/Rscript" --vanilla --default-packages= -e "tools::buildVignettes(dir = '.', tangle = TRUE)"' had status 1
 ERROR
Warning in engine$weave(file, quiet = quiet, encoding = enc) :
  Pandoc (>= 1.12.3) and/or pandoc-citeproc is not available. Please install both.
Quitting from lines 19-42 (A_Introduction.Rmd) 
Error: processing vignette 'A_Introduction.Rmd' failed with diagnostics:
the table must have a header (column names)
Execution halted
Error: Command failed (1)
Execution halted
Build step 'Execute R script' marked build as failure
```

**Comment by lawinslow** [comment]
@ldecicco-USGS

**Comment by ldecicco-USGS** [comment]
This is on your computer?

**Comment by lawinslow** [comment]
worker machine. Hmmm

**Comment by ldecicco-USGS** [comment]
hmm...I had forgotten to add --as-cran to my check. I'll see what pops up. But, I'd be surprised if we didn't need pandoc installed. I've never seen that error. 

I can't get rid of one NOTE: "The following directory looks like a leftover from 'knitr':
  'figure'" because there are so many images. But, that's not the error. 

There's also now a as-cran NOTE that it's too big...again, I'm ignoring

**Comment by ldecicco-USGS** [comment]
(if I add vignette/figure to.Rbuildignore, the build_vignette function doesn't work)

**Comment by lawinslow** [comment]
Looks to be a path issue. pandoc wasn't available to jenkins. I might have it fixed now.

**Comment by lawinslow** [comment]
OMFG pandoc

**Comment by ldecicco-USGS** [comment]
:-1: sorry

**Pull request merged**
